language: go
go:
  - 1.5

before_install:
  - go get -v golang.org/x/tools/cmd/vet
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/go-playground/overalls
  - go get -v github.com/mattn/goveralls

install:
  - go install -race -v std
  - go get -race -t -v ./...
  - go install -race -v ./...

script:
  - "$HOME/gopath/bin/golint ."
  - go test -timeout 1s -cpu=2 -race -v ./...
  - go test -timeout 1s -cpu=2 -covermode=atomic ./...
  - overalls -project=github.com/s2gatev/sqlmorph
  - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci
